### ISSUE TITLE
CI builds are failing

### ISSUE THREAD

**Issue by simonknittel** [simonknittel/static-site-generator#89]
```
> SET-PROJECT-NAME@ test /home/rof/src/github.com/simonknittel/static-site-generator
> karma start karma.conf.js && gulp

19 10 2016 16:04:18.091:ERROR [plugin]: Error during loading "karma-phantomjs-launcher" plugin:
Path must be a string. Received null
19 10 2016 16:04:18.644:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
19 10 2016 16:04:18.645:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
19 10 2016 16:04:18.647:ERROR [karma]: Found 1 load error
[16:04:19] Requiring external module babel-register
fs.js:951
return binding.readdir(pathModule._makeLong(path), options.encoding);
^

Error: ENOENT: no such file or directory, scandir '/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/vendor'
at Error (native)
at Object.fs.readdirSync (fs.js:951:18)
at Object.getInstalledBinaries (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/extensions.js:119:13)
at foundBinariesList (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/errors.js:45:5)
at Object.<anonymous> (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/index.js:15:28)
at Module._compile (module.js:570:32)
at Module._extensions..js (module.js:579:10)
at Object.require.extensions.(anonymous function) [as .js] (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/babel-register/lib/node.js:152:7)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/gulp-sass/index.js:187:21)
npm ERR! Test failed.  See above for more details.
```

**Comment by simonknittel** [comment]
```
> SET-PROJECT-NAME@ test /home/rof/src/github.com/simonknittel/static-site-generator
> karma start karma.conf.js && gulp

29 10 2016 10:25:57.597:ERROR [plugin]: Error during loading "karma-phantomjs-launcher" plugin:
Path must be a string. Received null
29 10 2016 10:25:58.092:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
29 10 2016 10:25:58.093:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
29 10 2016 10:25:58.095:ERROR [karma]: Found 1 load error
[10:25:58] Requiring external module babel-register
/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/index.js:13
throw new Error(errors.unsupportedEnvironment());
^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
at Object.<anonymous> (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/node-sass/lib/index.js:13:11)
at Module._compile (module.js:573:32)
at Module._extensions..js (module.js:582:10)
at Object.require.extensions.(anonymous function) [as .js] (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/babel-register/lib/node.js:152:7)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
at Function.Module._load (module.js:441:3)
at Module.require (module.js:500:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/gulp-sass/index.js:187:21)
at Module._compile (module.js:573:32)
at Module._extensions..js (module.js:582:10)
at Object.require.extensions.(anonymous function) [as .js] (/home/rof/src/github.com/simonknittel/static-site-generator/node_modules/babel-register/lib/node.js:152:7)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
at Function.Module._load (module.js:441:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by simonknittel** [comment]
Resetting the dependency cache on Codeship fixed the issue

**Comment by simonknittel** [comment]
Works for Travis CI too

**Comment by simonknittel** [comment]
Seems like generally fixed
